spring:
  profiles:
    active: local

server:
  port: 1979
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60s

logging:
  level:
    # root: debug
    kelly:
      backend: debug
  pattern:
    file: "%d{yy-MM-dd HH:mm:ss.SSS} %-5level ${PID:-} --- [%thread] [%logger{0}:%line] - %msg%n"
    console: "%d{yy-MM-dd HH:mm:ss.SSS} %-5level ${PID:-} --- [%thread] [%logger{0}:%line] - %msg%n"
  file:
    name: E:/Repository/Logs/kelly-backend/kelly-backend.log  # name 과 path 는 분리해서 사용 안됨.
    # path: E:/Repository/Logs/kelly-backend
  logback:
    rollingpolicy:
      file-name-pattern: ${logging.file.name}.%d{yyyy-MM-dd}.%i.log.zip
      max-file-size: 100MB
      max-history: 60
      total-size-cap: 1GB
